### ISSUE TITLE
Extension not starting in AE

### ISSUE THREAD

**Issue by SteveLewisZA** [Inventsable/bombino#13]
Hi there,

I'm coming back to using this after some time and I'm now facing an issue where the extension is not showing or opening at all when I click on it through Window > Extensions, I previously faced this issue some months ago but it was resolved by setting up debugging unsigned extensions with PlayerDebugMode, but now even after ensuring that value is set to 1, I am facing the same issue, could it be a problem with the newer version of AE?

I'm simply trying to run the un-changed bombino-brutalism-router template, it appears in the Extensions menu, but clicking it does nothing, not sure if there's something else I could be doing wrong here? and not sure where to start to debug this issue, any assistance would be greatly appriciated!

Many thanks,
Steve

**Comment by Inventsable** [comment]
Hey Steve,

This may be related to the prior issue since the new apps are using CEP 10, [which requires another distinct registry change](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_10.x/Documentation/CEP%2010.0%20HTML%20Extension%20Cookbook.md#debugging-unsigned-extensions) for `CSXS.10` (where it was previously `CSXS.9` for CEP 9). Just to confirm, you didn't make a registry change, and the template does work for 2020 apps and below?

**Comment by SteveLewisZA** [comment]
Oh wow, you're right, I just didn't see the new CSXS.10 in registery because it's listed before all others, thank you!!

**Comment by Inventsable** [comment]
No worries -- that even happened to me too! I thought there was none because I didn't realize 10 was at the top and was stumped for a while. Let me know if there's anything else, otherwise closing for now. Thanks
