### ISSUE TITLE
Debugging the panel

### ISSUE THREAD

**Issue by zync09** [Inventsable/bombino#23]
Hi again,

Thanks for your help earlier today. So I've gotten to a stage where I've got some elements in my panel and Vue is working nicely with it too. But I can't for anything seem to be able to debug stuff with console.log. Not sure if there is a better way too. 

My .debug file is:
![bm2](https://user-images.githubusercontent.com/4277442/133671491-814fe4ac-a102-42dd-8b1a-776789bf0857.png)

And I can get to Chrome and see the debug screen. But nothing seems to be tracing. I do get a 
document.registerElement is not a function

not sure if it's my code or default panel setup. error like the one below.

`UI.themeSupport=new UI.ThemeSupport(themeSetting);UI.themeSupport.applyTheme(document);var body=(document.body);UI.appendStyle(body,'ui/inspectorStyle.css');UI.GlassPane.setContainer((document.body));};UI.beautifyFunctionName=function(name){return name||Common.UIString('(anonymous)');};UI.registerCustomElement=function(localName,typeExtension,prototype){return document.registerElement(typeExtension,{prototype:Object.create(prototype),extends:localName});};UI.createTextButton=function(text,clickHandler,className,primary){var element=createElementWithClass('button',className||'','text-button');element.textContent=text;if(primary)`

![bm1](https://user-images.githubusercontent.com/4277442/133670899-a21598a3-bc24-4591-a640-88d146bfd1b5.PNG)

**Comment by Inventsable** [comment]
Hello again. You actually have to use a standalone program called [CEFClient instead of Chrome](https://github.com/Adobe-CEP/CEP-Resources/tree/master/CEP_10.x/Cefclient_v74) otherwise you'd get that `document.register error`, with the syntax `http://localhost:[NUMBER]` (must be http, not https, etc). You can technically open brutalism panels in browser (like in a normal Chrome page) but it requires [a few steps shown here](https://github.com/battleaxedotco/bombino-brutalism-basic#use-in-browser).

**Comment by zync09** [comment]
Wow I didn't even know that CEFClient existed. So much has changed since I last attempted this. Thanks again for a point in the right direction. All working well.

**Comment by Inventsable** [comment]
No worries. And yes lol, we used to be able to use vanilla Chrome but have had to use CEF Client since CEP 10 iirc, I think that change happened late 2019ish.

**Comment by zync09** [comment]
I don't suppose there is a way to use VueDevtools from inside that CEF?

**Comment by Inventsable** [comment]
The only way I know of is to run the panel in Chrome with the link above because this gives you access to normal DevTools and any browser extensions, but this typically means you don't have interaction with the host app. I do this often using (and returning) mock data with evalScript calls to effectively fake things. We can probably do things entirely in browser and allow app interaction but this would require some kind of WebSocket connection and a standalone invisible CEP extension. I've been meaning to look into it but generally flip to browser versions of my UI when Vue DevTools is needed just for ease/convenience.

**Comment by Inventsable** [comment]
You might be able to install extensions in CEFClient, but apparently it will break when you update it. If you find a way I'd be curious to know!

**Comment by zync09** [comment]
Ah righto I see. Cheers mate. I'll give it a shot and report back here. Technically CEF is just running Chromium so should be possible.

**Comment by Inventsable** [comment]
Deal! Feel free to post back or reopen if you find or need help with anything.

**Comment by zync09** [comment]
OK so found a way. Turns out we shouldn't need to use the CEF app too - can just use Chrome and Vue Dev tools.

What I did was run:
`chrome://inspect/#devices` in Chrome.

Then make sure that **port forwarding** is setup (press port forwarding and then tick down bottom)
Then **Configure** Network targets and add

`localhost:8888` which is my vue web server in bombino
(as I have another nginx what I use for normal dev work already running on 8080

Refresh the page and you should see your Extension in there, then just press **inspect**.
![bm3](https://user-images.githubusercontent.com/4277442/133710812-c777638b-d96f-410c-8d5a-f0752242b3c7.PNG)

While you can't interact with the preview there you can still use the select element on part of the preview to help debugging easier though which is nice. 

However. I Couldn't get vue devtools to run in here with those tabs you see tot he right. One is for vue 2, the other vue 3.

So Plan B.

https://devtools.vuejs.org/guide/installation.html#settings-1
`npm install --save-dev @vue/devtools` install dev tools to the app

And in main.js import devtools and connect too your local ip for testing.

![image](https://user-images.githubusercontent.com/4277442/133711225-aec231e5-e1cb-4cd5-9632-4f792abd73df.png)

Then run vue-devtools from your Vscode shell or other.

`vue-devtools`

you might need to install it globall if that doesn't work and try again though. I did both app and global.

`npm install -g @vue/devtools`

From there you should have console logging in Chrome inspect and then Vue debugging from Remote Vue Dev tools.

Sorry I'm on an ultrawide so might have to zoom in.

Thanks again mate for pointing me in the right direction. Do you have a discord or something or best place to ask for questions and potentially solve them still here on the issues section?

![bm10](https://user-images.githubusercontent.com/4277442/133711469-580e1eba-85d7-4ac7-b8e9-94d20512f4d0.PNG)
