### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'root' before initialization

### ISSUE THREAD

**Issue by Jean-Zombie** [Inventsable/bombino#28]
Hey there! 
After a fresh and unaltered install with bombino my `bombino-vue-basic` panel is not rendering. As suggested I am checking the CEF client in Chrome at `localhost:8888`. The module `cep-spy` is throwing `Uncaught ReferenceError: Cannot access 'root' before initialization` error. Am I doing something wrong?

**Comment by Inventsable** [comment]
Hi all,

I've transferred this issue here because it isn't specific to the template where the issue was published and is largely caused by `cep-spy` which is one of the core dependencies of bombino. Presumably any one who comes across this problem will be able to much more easily find it here than in it's original location.

I am going to go ahead and close this for now under the assumption all templates are fixed. If you can replicate this in any way after today's date, feel free to re-open it and notify me.
